import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'react-datepicker/dist/react-datepicker.css'
import { cn } from "@/lib/utils";
import Header from "@/features/layout/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <html lang="en" className="h-full" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          'h-full bg-background font-sans antialiased',
          inter.className
        )}
      >
          <div className="relative flex min-h-screen flex-col ">
            <Header />
            <div className="flex-1">{children}</div>
          </div>
      </body>
    </html>
  </>
  );
}
